# Site settings
title: 書くためのブログ
description: |
  webデザインや開発にまつわるネタを書きとめていくブログです。
baseurl: ""
url: https://kakutame.com
twitter_username: bennkyougirai
github_username:  m-yoshiro

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-archives
  - jekyll-seo-tag

sass:
  sass_dir: assets/_sass
  style: :compressed

jekyll-archives:
  enabled:
    - tags

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
